//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string EmpFirst { get; set; }
        public string EmpLast { get; set; }
        public int EmpSalary { get; set; }
        public System.DateTime EmpStart { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
