//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementTools
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CMTEntities2 : DbContext
    {
        public CMTEntities2()
            : base("name=CMTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annual_Incomes> Annual_Incomes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("CMTEntities2", "ufn_GetProfit")]
        public virtual IQueryable<ufn_GetProfit_Result> ufn_GetProfit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_GetProfit_Result>("[CMTEntities2].[ufn_GetProfit]()");
        }
    }
}
